### ISSUE TITLE
How do I use a custom plugin with qwc2

### ISSUE THREAD

**Issue by nickhrm** [qgis/qwc2#433]
I am trying to use a custom plugin, which is currently just a short hello world plugin:
The code is in the following file: QWC2-DEMO-APP/js/plugins/MyPlugin.jsx

```react // Datei: js/plugins/MyPlugin.jsx
import React from 'react';
import { connect } from 'react-redux';

import { setCurrentTask } from 'qwc2/actions/task';  // QWC2 Aktion zum Setzen des aktuellen Tasks

import PropTypes from 'prop-types';

export class MyPlugin extends React.Component {
    // Das Plugin rendert nur etwas, wenn es der aktuelle "Task" ist
    // console.log("Geschaffft!!!");
    render() {
        if (this.props.currentTask === 'MyPlugin') {
            return (
                <div className="myplugin-panel">
                    <h2>Hallo von MyPlugin</h2>
                    <p>Dies ist ein eigenes Plugin-Panel.</p>
                    {/* Button zum Schließen des Panels */}
                    <button onClick={() => this.props.dispatch(setCurrentTask(null))}>
                        Schließen
                    </button>
                </div>
            );
        }
        return null;  // Nichts anzeigen, wenn das Plugin nicht aktiv ist
    }
}

MyPlugin.propTypes = {
    currentTask: PropTypes.string,
    dispatch: PropTypes.func.isRequired
};

// Redux-State (aktueller Task) als Prop bereitstellen
const mapStateToProps = state => ({
    currentTask: state.task ? state.task.id : null
});
export default connect(mapStateToProps)(MyPlugin);
 ```

Here are the steps i took: 
1. I added  "MyPlugin: MyPlugin," to the list of plugins at pluginsDef.plugins in the QWC2-DEMO-APP/js/AppConfig.js
2. I ran npm run prod and copied the content of the QWC2-DEMO-APP/prod folder into the QWC-DOCKER/volumes/qwc2 folder
3. I updated the QWC-DOCKER/docker-compose.yml: 

```yaml  qwc-map-viewer:
    # Stock qwc2 app
    #image: sourcepole/qwc-map-viewer:latest-2025-lts
    # Or with own viewer build placed in volumes/qwc2
    image: sourcepole/qwc-map-viewer-base:latest-2025-lts
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/'
    volumes:
      - ./pg_service.conf:/srv/pg_service.conf:ro
      - ./volumes/config:/srv/qwc_service/config:ro
      # When using qwc-map-viewer:
      #- ./volumes/qwc2/assets:/qwc2/assets:ro
      # When using own viewer build with qwc-map-viewer-base:
      - ./volumes/qwc2:/qwc2:ro
 ```

4.  I updated the QWC-DOCKER/volumes/default/config.json: added  { "key": "MyPlugin", "icon": "measure_line" } to plugins.common

5. ran docker-compose up

The plugin is not loaded and i get the console warning: "Non-existing plugin: MyPlugin"

The steps I took are fro mthis documentation under the title "Building a custom viewer":
https://qwc-services.github.io/2024-lts/configuration/ViewerConfiguration/#separate-mobile-desktop-global-settings
